sources:
  - name: airbnb_source_name
    database: airbnb-project-499912
    schema: dev_analytics

    tables:
      - name: bookings
        #<1 day pass, 1-3 warn, >3 error 
        loaded_at_field: created_at

        freshness:
          warn_after:
            count: 1
            period: day
          error_after:
            count: 365
            period: day


      - name: listings
      - name: hosts

models:
  - name: stg_bookings
    columns:
      
      - name: booking_id
        data_tests:
          - not_null
          - unique
      
      - name: nights_booked
        data_test:
          min_nights
    

  - name: stg_listings
    columns:
      - name: property_type
        data_tests:
          - accepted_values:
              values: ["House","Condo","Apartment"]
        


